import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

/**
 * The Drizzle migrator only runs a migration when its journal `when` is greater
 * than the newest `created_at` already recorded in `drizzle.__drizzle_migrations`
 * (see drizzle-orm/pg-core/dialect.cjs). A migration whose `when` is lower than an
 * earlier one is skipped silently: no error, and the boot log still says
 * "Database migrations applied". These tests catch that before it reaches a database.
 */

const MIGRATIONS_DIR = path.join(__dirname, '..', 'migrations')

type JournalEntry = {
  idx: number
  version: string
  when: number
  tag: string
  breakpoints: boolean
  dialect: string
}

const journal: { entries: JournalEntry[] } = JSON.parse(
  fs.readFileSync(path.join(MIGRATIONS_DIR, 'meta', '_journal.json'), 'utf-8')
)

/**
 * Pre-existing violation, kept out of the assertion on purpose. 0012 was generated by
 * drizzle-kit with its real timestamp, which landed before the hand-picked `when` of
 * 0011. It still got applied because the migrator reads the newest applied migration
 * once before the loop, so 0011 and 0012 were compared against the same older baseline
 * in a single run. Do not add entries here — fix the `when` instead.
 */
const KNOWN_LEGACY_REGRESSIONS = ['0012_daily_black_crow']

describe('migrations journal', () => {
  it('has a strictly increasing `when` across entries', () => {
    const regressions: string[] = []
    let highest = -Infinity

    for (const entry of journal.entries) {
      if (entry.when <= highest) {
        regressions.push(`${entry.tag} (when=${entry.when}, highest so far=${highest})`)
      }
      highest = Math.max(highest, entry.when)
    }

    const unexpected = regressions.filter(
      (r) => !KNOWN_LEGACY_REGRESSIONS.some((tag) => r.startsWith(tag))
    )

    expect(unexpected).toEqual([])
  })

  it('has sequential idx values starting at 0', () => {
    expect(journal.entries.map((e) => e.idx)).toEqual(journal.entries.map((_, i) => i))
  })

  it('has a .sql file for every journal entry', () => {
    const missing = journal.entries
      .map((e) => `${e.tag}.sql`)
      .filter((file) => !fs.existsSync(path.join(MIGRATIONS_DIR, file)))

    expect(missing).toEqual([])
  })

  it('has a journal entry for every .sql file', () => {
    const tags = new Set(journal.entries.map((e) => e.tag))
    const orphans = fs
      .readdirSync(MIGRATIONS_DIR)
      .filter((file) => file.endsWith('.sql'))
      .filter((file) => !tags.has(file.replace(/\.sql$/, '')))

    expect(orphans).toEqual([])
  })
})
